# Generated by Django 5.0 on 2025-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='schedule_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
