# Generated by Django 5.1.5 on 2025-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='reward',
            field=models.CharField(default='ice'),
        ),
    ]
