# Generated by Django 5.1.5 on 2025-02-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customusers_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
