# Generated by Django 5.1.5 on 2025-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_medals_usermedals'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2025-03-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusers',
            name='last_active_date',
            field=models.DateField(null=True),
        ),
    ]
