# Generated by Django 5.1.5 on 2025-03-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customusers_created_at_customusers_last_active_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='created_at',
        ),
    ]
