# Generated by Django 5.1.5 on 2025-03-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_customusers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='description',
            field=models.TextField(default='У тебя пока нет описания, но ты можешь добавить его в настройках'),
        ),
    ]
