# Generated by Django 5.1.5 on 2025-04-03 12:54

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_customusers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='description',
            field=models.CharField(default='У тебя пока нет описания, но ты можешь добавить его в настройках', max_length=128),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.', 'invalid_choice': 'Value %(value)r is not a valid choice.', 'null': 'This field cannot be null.', 'unique': 'A user with that username already exists.', 'unique_for_date': '%(field_label)s must be unique for %(date_field_label)s %(lookup_type)s.'}, help_text='Required. 18 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=18, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MaxLengthValidator(150)], verbose_name='username'),
        ),
    ]
