# Generated by Django 5.1.5 on 2025-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_customusers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
