# Generated by Django 5.1.5 on 2025-03-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_goalstemplateactive_taskstemplateactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstemplateactive',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goals.goalstemplateactive'),
        ),
    ]
