# Generated by Django 5.1.5 on 2025-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0003_alter_taskstemplateactive_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstemplateactive',
            name='spent_time',
            field=models.IntegerField(default=0),
        ),
    ]
