# Generated by Django 5.1.5 on 2025-03-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0004_alter_taskstemplateactive_spent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstemplateactive',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
