# Generated by Django 5.1.5 on 2025-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0006_userdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdays',
            name='date',
            field=models.DateField(),
        ),
    ]
