# Generated by Django 5.1.5 on 2025-02-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medals',
            name='img',
            field=models.URLField(default=None),
        ),
    ]
