# Generated by Django 5.1.5 on 2025-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medals', '0002_medals_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='medals',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medals',
            name='img',
            field=models.URLField(),
        ),
    ]
